In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cd

/home/pr1407

In [3]:
cd

/home/pr1407

In [4]:
cd "ED-LP"

[Errno 2] No such file or directory: 'ED-LP'
/home/pr1407

In [5]:
cd "ED-Lab"

/home/pr1407/ED-Lab

In [6]:
cd "Caso 1"

/home/pr1407/ED-Lab/Caso 1

In [7]:
dataframe = pd.read_csv('smartphone_activity_dataset.csv')

In [8]:
dataframe.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_553,feature_554,feature_555,feature_556,feature_557,feature_558,feature_559,feature_560,feature_561,activity
0,0.289,-0.0203,-0.133,-0.995,-0.983,-0.914,-0.995,-0.983,-0.924,-0.935,...,-0.299,-0.710,-0.1130,0.03040,-0.465,-0.0184,-0.841,0.180,-0.0586,5
1,0.278,-0.0164,-0.124,-0.998,-0.975,-0.960,-0.999,-0.975,-0.958,-0.943,...,-0.595,-0.861,0.0535,-0.00743,-0.733,0.7040,-0.845,0.180,-0.0543,5
2,0.280,-0.0195,-0.113,-0.995,-0.967,-0.979,-0.997,-0.964,-0.977,-0.939,...,-0.391,-0.760,-0.1190,0.17800,0.101,0.8090,-0.849,0.181,-0.0491,5
3,0.279,-0.0262,-0.123,-0.996,-0.983,-0.991,-0.997,-0.983,-0.989,-0.939,...,-0.117,-0.483,-0.0368,-0.01290,0.640,-0.4850,-0.849,0.182,-0.0477,5
4,0.277,-0.0166,-0.115,-0.998,-0.981,-0.990,-0.998,-0.980,-0.990,-0.942,...,-0.351,-0.699,0.1230,0.12300,0.694,-0.6160,-0.848,0.185,-0.0439,5

In [9]:
y = dataframe['activity']
x = dataframe.drop('activity', axis=1)

In [10]:
x

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_552,feature_553,feature_554,feature_555,feature_556,feature_557,feature_558,feature_559,feature_560,feature_561
0,0.289,-0.0203,-0.1330,-0.995,-0.9830,-0.914,-0.995,-0.983,-0.924,-0.93500,...,-0.0743,-0.2990,-0.710,-0.1130,0.03040,-0.465,-0.0184,-0.841,0.180,-0.0586
1,0.278,-0.0164,-0.1240,-0.998,-0.9750,-0.960,-0.999,-0.975,-0.958,-0.94300,...,0.1580,-0.5950,-0.861,0.0535,-0.00743,-0.733,0.7040,-0.845,0.180,-0.0543
2,0.280,-0.0195,-0.1130,-0.995,-0.9670,-0.979,-0.997,-0.964,-0.977,-0.93900,...,0.4150,-0.3910,-0.760,-0.1190,0.17800,0.101,0.8090,-0.849,0.181,-0.0491
3,0.279,-0.0262,-0.1230,-0.996,-0.9830,-0.991,-0.997,-0.983,-0.989,-0.93900,...,0.4050,-0.1170,-0.483,-0.0368,-0.01290,0.640,-0.4850,-0.849,0.182,-0.0477
4,0.277,-0.0166,-0.1150,-0.998,-0.9810,-0.990,-0.998,-0.980,-0.990,-0.94200,...,0.0878,-0.3510,-0.699,0.1230,0.12300,0.694,-0.6160,-0.848,0.185,-0.0439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10294,0.310,-0.0534,-0.0991,-0.288,-0.1410,-0.215,-0.356,-0.149,-0.232,0.18500,...,0.0745,-0.3760,-0.751,-0.3370,0.34600,0.885,-0.6990,-0.652,0.275,0.1850
10295,0.363,-0.0392,-0.1060,-0.305,0.0281,-0.196,-0.374,-0.030,-0.270,0.18500,...,0.1020,-0.3200,-0.700,-0.7370,-0.37300,-0.657,0.3230,-0.655,0.274,0.1820
10296,0.350,0.0301,-0.1160,-0.330,-0.0421,-0.250,-0.388,-0.133,-0.347,0.00747,...,-0.0662,-0.1190,-0.467,-0.1820,0.08860,0.697,0.3630,-0.655,0.274,0.1810
10297,0.238,0.0185,-0.0965,-0.323,-0.2300,-0.208,-0.392,-0.280,-0.289,0.00747,...,-0.0465,-0.2050,-0.618,0.4450,-0.81900,0.929,-0.0084,-0.660,0.265,0.1880
10298,0.154,-0.0184,-0.1370,-0.330,-0.1950,-0.164,-0.431,-0.218,-0.230,-0.11200,...,-0.0104,-0.0722,-0.437,0.5990,-0.28800,0.876,-0.0250,-0.660,0.264,0.1880

In [11]:
y

0        5
1        5
2        5
3        5
4        5
        ..
10294    2
10295    2
10296    2
10297    2
10298    2
Name: activity, Length: 10299, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=45)

In [14]:
x_train

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_552,feature_553,feature_554,feature_555,feature_556,feature_557,feature_558,feature_559,feature_560,feature_561
6273,0.264,-0.03330,-0.0527,-0.9310,-0.8070,-0.7630,-0.952,-0.81500,-0.7770,-0.835,...,-0.3400,0.568,0.3020,0.0625,-0.0225,-0.9710,0.596,-0.762,0.2580,0.0584
5390,0.294,-0.01830,-0.1200,-0.6270,-0.2170,-0.4250,-0.649,-0.25400,-0.4180,-0.547,...,0.0940,0.527,0.3490,-0.4150,-0.4890,0.0959,-0.297,-0.857,0.1840,-0.0349
8492,0.374,-0.02380,-0.0823,-0.0774,-0.0711,-0.3270,-0.148,-0.12300,-0.3300,0.101,...,0.1290,-0.149,-0.5140,-0.7370,0.6040,0.8940,0.744,-0.911,0.0496,-0.0273
1633,0.277,-0.01080,-0.1140,-0.9990,-0.9760,-0.9990,-0.999,-0.97600,-0.9980,-0.944,...,0.2350,-0.407,-0.7270,0.0746,-0.1030,-0.8430,0.298,-0.903,0.1440,-0.0341
4326,0.265,-0.03470,-0.0881,-0.3680,-0.0745,-0.2300,-0.394,-0.08240,-0.2440,-0.261,...,0.1550,0.199,-0.0462,0.0375,-0.9040,0.6150,-0.611,-0.602,0.3360,0.1570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,0.208,-0.00314,-0.1150,-0.9680,-0.9320,-0.9340,-0.973,-0.94000,-0.9340,-0.917,...,-0.1380,-0.259,-0.6670,-0.2120,0.1860,-0.2720,0.813,0.447,-0.8820,0.0917
163,0.317,-0.02390,-0.1110,-0.4210,-0.0055,-0.0179,-0.462,0.04970,0.0656,-0.198,...,0.2570,-0.488,-0.8070,-0.9400,-0.6470,-0.7530,0.142,-0.667,0.3250,0.0556
6012,0.242,0.00857,-0.1470,0.2370,-0.1310,-0.2860,0.217,-0.16000,-0.3370,0.216,...,-0.1050,-0.228,-0.6020,0.3130,-0.6530,0.9420,0.634,-0.870,0.1880,0.0110
6558,0.200,-0.01020,-0.1310,-0.2560,0.0112,-0.1690,-0.299,-0.00231,-0.2040,-0.235,...,-0.0496,-0.196,-0.6380,0.6520,-0.6440,-0.7170,0.228,-0.758,0.2360,0.1140
7115,0.231,-0.04050,-0.0241,-0.2000,-0.2670,-0.4090,-0.282,-0.26500,-0.3820,0.197,...,0.1320,-0.234,-0.6270,0.1800,0.1960,-0.8070,-0.664,-0.858,0.1950,0.0346

In [15]:
y_train

6273    5
5390    1
8492    1
1633    5
4326    1
       ..
8772    6
163     2
6012    3
6558    1
7115    3
Name: activity, Length: 7209, dtype: int64

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn = KNeighborsClassifier(n_neighbors=1)

In [18]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [19]:
predicciones = knn.predict(x_test)

In [20]:
y_test

8762    4
9694    1
2995    1
2440    6
4821    1
       ..
2262    4
8126    5
5053    2
3338    6
702     5
Name: activity, Length: 3090, dtype: int64

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predicciones))
print(classification_report(y_test,predicciones))

[[502   0   1   0   0   0]
 [  1 474   0   0   0   0]
 [  1   3 424   0   0   0]
 [  0   0   0 479  42   0]
 [  0   0   0  54 513   0]
 [  0   0   0   0   0 596]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       503
           2       0.99      1.00      1.00       475
           3       1.00      0.99      0.99       428
           4       0.90      0.92      0.91       521
           5       0.92      0.90      0.91       567
           6       1.00      1.00      1.00       596

    accuracy                           0.97      3090
   macro avg       0.97      0.97      0.97      3090
weighted avg       0.97      0.97      0.97      3090

In [ ]:
tasa_error = []
for i in range(1,30):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    prediccion_i = knn.predict(x_test)
    tasa_error.append(np.mean(prediccion_i != y_test))

In [ ]:
tasa_error

In [ ]:
valores = range(1,30)
plt.plot(valores, tasa_error, color='green', marker='o',markerfacecolor = 'red', markersize='8')